//USERS
export const FETCH_USERS = "FETCH_USERS";
export const FETCH_FIRST_USER = "FETCH_FIRST_USER";
export const FETCH_MORE_USERS = "FETCH_MORE_USERS";
export const LINK_TO_NEXT_PAGE = "LINK_TO_NEXT_PAGE";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";
export const FETCH_FIRST_USER_ERROR = "FETCH_FIRST_USER_ERROR";

//FORM
export const FETCH_POSITIONS = "FETCH_POSITIONS";
export const FETCH_TOKEN = "FETCH_TOKEN";

export const CHECK_NAME = "CHECK_NAME";
export const CHECK_EMAIL = "CHECK_EMAIL";
export const CHECK_PHONE = "CHECK_PHONE";
export const CHECK_POSITION = "CHECK_POSITION";
export const CHECK_PHOTO = "CHECK_PHOTO";

export const CLEAR_FORM_DATA = "CLEAR_FORM_DATA";
export const SHOW_MODAL = "SHOW_MODAL";
